<dl class="news_list clearfix">
          
          <dt>2017.09.11<img src="/resource/img/press.png" alt="プレスリリース" class="category pc press"><img src="/resource/img/sp/press.png" alt="プレスリリース" class="category sp press"></dt>
          
          <dd>
            
            
              
                <a href="https://e-lcs.jp/news/detail/000039.html">
              
              
            
            2016年度 CO2排出実績（速報値）について
            
            
            </a>
            
          </dd>
          
          <dt>2017.07.01<img src="/resource/img/public.png" alt="公表情報" class="category pc public"><img src="/resource/img/sp/public.png" alt="公表情報" class="category sp public"></dt>
          
          <dd>
            
            
              
                <a href="https://e-lcs.jp/news/detail/000035.html">
              
              
            
            「電気事業低炭素社会協議会」理事の交代について
            
            
            </a>
            
          </dd>
          
          <dt>2017.06.19<img src="/resource/img/public.png" alt="公表情報" class="category pc public"><img src="/resource/img/sp/public.png" alt="公表情報" class="category sp public"></dt>
          
          <dd>
            
            
              
                <a href="https://e-lcs.jp/news/detail/000034.html">
              
              
            
            「電気事業低炭素社会協議会」理事・監事の選任について
            
            
            </a>
            
          </dd>
          
          <dt>2017.06.19<img src="/resource/img/public.png" alt="公表情報" class="category pc public"><img src="/resource/img/sp/public.png" alt="公表情報" class="category sp public"></dt>
          
          <dd>
            
            
              
                <a href="https://e-lcs.jp/news/detail/000037.html">
              
              
            
            「電気事業低炭素社会協議会」2017年度 第１回 通常総会について
            
            
            </a>
            
          </dd>
          
          <dt>2017.04.05<img src="/resource/img/public.png" alt="公表情報" class="category pc public"><img src="/resource/img/sp/public.png" alt="公表情報" class="category sp public"></dt>
          
          <dd>
            
            
              
                <a href="https://e-lcs.jp/news/detail/000032.html">
              
              
            
            会員事業者の異動について
            
            
            </a>
            
          </dd>
          
        </dl>
        <div class="link_btn">
         <p><a href="/news/" class="blue-btn">一覧をみる　<i class="fa fa-chevron-right" aria-hidden="true"></i></a></p>
        </div>

